name: Purge jsDelivr Cache
on:
  release:
    types: [published]

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/freddy-schuetz/n8n-claw-templates@latest/templates/index.json
